name: Build and Package applications

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-headless-daemon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Get daemon dependencies
        run: |
          cd apps/headless_daemon
          dart pub get

      - name: Compile Headless Daemon EXE
        run: |
          cd apps/headless_daemon
          mkdir -p build
          dart compile exe bin/main.dart -o build/headless_daemon

      - name: Upload Headless Daemon Artifact
        uses: actions/upload-artifact@v4
        with:
          name: headless-daemon-linux
          path: apps/headless_daemon/build/headless_daemon

  build-flutter-client-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      - name: Recreate Windows scaffolding
        run: |
          cd apps/client_flutter
          flutter create --platforms=windows .

      - name: Get client dependencies
        run: |
          cd apps/client_flutter
          flutter pub get

      - name: Build Windows App
        run: |
          cd apps/client_flutter
          flutter build windows --release --verbose

      - name: Upload Windows App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-flutter-windows
          path: apps/client_flutter/build/windows/x64/runner/Release/
